export enum AssetKeys {
  BACKGROUND = "BACKGROUND",
  DINO_ATLAS_SPINOSAURUS = "DINO_ATLAS_SPINOSAURUS",
  DINO_ATLAS_TYRANNOSAURUS = "DINO_ATLAS_TYRANNOSAURUS",
  DINO_FACE_SPINOSAURUS = "DINO_FACE_SPINOSAURUS",
  DINO_FACE_TYRANNOSAURUS = "DINO_FACE_TYRANNOSAURUS",
  CLOUD_1 = "CLOUD_1",
  CLOUD_2 = "CLOUD_2",
  CACTUS_1 = "CACTUS_1",
  CACTUS_2 = "CACTUS_2",
  CACTUS_3 = "CACTUS_3",
  DIED = "DIED",
}
